[package]
name = "core-rpc"
version = "0.14.0"
authors = [
    "Steven Roose <steven@stevenroose.org>",
    "Jean Pierre Dudey <jeandudey@hotmail.com>",
    "Dawid Ciężarkiewicz <dpc@dpc.pw>",
    "Riccardo Casatta <riccardo@casatta.it>",
]
license = "CC0-1.0"
homepage = "https://github.com/RCasatta/rust-bitcoincore-rpc/"
repository = "https://github.com/RCasatta/rust-bitcoincore-rpc/"
description = "RPC client library for the Bitcoin Core JSON-RPC API."
keywords = ["crypto", "bitcoin", "bitcoin-core", "rpc"]
readme = "README.md"

[lib]
name = "core_rpc"
path = "src/lib.rs"

[dependencies]
core-rpc-json = { version = "0.14.0", path = "../json" }

log = "0.4.5"
jsonrpc = "0.12.0"

# Used for deserialization of JSON.
serde = "1"
serde_json = "1"
