[package]
name = "core-rpc-json"
version = "0.14.0"
authors = [
    "Steven Roose <steven@stevenroose.org>",
    "Jean Pierre Dudey <jeandudey@hotmail.com>",
    "Dawid Ciężarkiewicz <dpc@dpc.pw>",
    "Riccardo Casatta <riccardo@casatta.it>",
]
license = "CC0-1.0"
homepage = "https://github.com/RCasatta/rust-bitcoincore-rpc/"
repository = "https://github.com/RCasatta/rust-bitcoincore-rpc/"
description = "JSON-enabled type structs for bitcoincore-rpc crate."
keywords = [ "crypto", "bitcoin", "bitcoin-core", "rpc" ]
readme = "README.md"

[lib]
name = "core_rpc_json"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"

bitcoin = { version = "0.27", features = [ "use-serde" ] }
